// get bookings from all users
export const GET_ALL_BOOKINGS = 'GET_ALL_BOOKINGS';
export const GET_ALL_BOOKINGS_SUCCESS = 'GET_ALL_BOOKINGS_SUCCESS';
export const GET_ALL_BOOKINGS_FAIL = 'GET_ALL_BOOKINGS_FAIL';

// change booking status
export const CHANGE_BOOKING_STATUS = 'CHANGE_BOOKING_STATUS';
export const CHANGE_BOOKING_STATUS_SUCCESS = 'CHANGE_BOOKING_STATUS_SUCCESS';
export const CHANGE_BOOKING_STATUS_FAIL = 'CHANGE_BOOKING_STATUS_FAIL';
