export const GET_SUBSCRIPTIONS = 'GET_SUBSCRIPTIONS';
export const GET_SUBSCRIPTIONS_SUCCESS = 'GET_SUBSCRIPTIONS_SUCCESS';
export const GET_SUBSCRIPTIONS_FAIL = 'GET_SUBSCRIPTIONS_FAIL';

export const PUBLISH_SUBSCRIPTIONS = 'PUBLISH_SUBSCRIPTIONS';
export const PUBLISH_SUBSCRIPTIONS_SUCCESS = 'PUBLISH_SUBSCRIPTIONS_SUCCESS';
export const PUBLISH_SUBSCRIPTIONS_FAIL = 'PUBLISH_SUBSCRIPTIONS_FAIL';