// Select meal item
export const SELECT_MEAL = 'SELECT_MEAL';

export const CLEAR_SELECTED = 'CLEAR_SELECTED';

// send feedback
export const SEND_FEEDBACK = 'SEND_FEEDBACK';
export const SEND_FEEDBACK_SUCCESS = 'SEND_FEEDBACK_SUCCESS';
export const SEND_FEEDBACK_FAIL = 'SEND_FEEDBACK_FAIL';

export const CHANGE_CONFIGURATION = 'CHANGE_CONFIGURATION';