// send feedback
export const SEND_FEEDBACK = 'SEND_FEEDBACK';
export const SEND_FEEDBACK_SUCCESS = 'SEND_FEEDBACK_SUCCESS';
export const SEND_FEEDBACK_FAIL = 'SEND_FEEDBACK_FAIL';

export const ADD_ROOM_CATEGORY = 'ADD_ROOM_CATEGORY';
export const ADD_ROOM_CATEGORY_SUCCESS = 'ADD_ROOM_CATEGORY_SUCCESS';
export const ADD_ROOM_CATEGORY_FAIL = 'ADD_ROOM_CATEGORY_FAIL';

export const ADD_ROOM = 'ADD_ROOM';
export const ADD_ROOM_SUCCESS = 'ADD_ROOM_SUCCESS';
export const ADD_ROOM_FAIL = 'ADD_ROOM_FAIL';