export const UPDATE_TOTAL = 'UPDATE_TOTAL';
export const UPDATE_TOTAL_SUCCESS = 'UPDATE_TOTAL_SUCCESS';
export const UPDATE_TOTAL_FAIL = 'UPDATE_TOTAL_FAIL';

export const ADD_ORDER = 'ADD_ORDER';
export const ADD_ORDER_SUCCSESS = 'ADD_ORDER_SUCCSESS';
export const ADD_ORDER_FAIL = 'ADD_ORDER_FAIL';
