export const SET_CURRENT_ROOM_CATEGORY = 'SET_CURRENT_ROOM_CATEGORY';

export const GET_ROOM_CATEGORIES = 'GET_ROOM_CATEGORIES';
export const GET_ROOM_CATEGORIES_SUCCESS = 'GET_ROOM_CATEGORIES_SUCCESS';
export const GET_ROOM_CATEGORIES_FAIL = 'GET_ROOM_CATEGORIES_FAIL';

export const CREATE_ROOM_CATEGORIES = 'CREATE_ROOM_CATEGORIES';
export const CREATE_ROOM_CATEGORIES_SUCCESS = 'CREATE_ROOM_CATEGORIES_SUCCESS';
export const CREATE_ROOM_CATEGORIES_FAIL = 'CREATE_ROOM_CATEGORIES_FAIL';

export const EDIT_ROOM_CATEGORIES = 'EDIT_ROOM_CATEGORIES';
export const EDIT_ROOM_CATEGORIES_SUCCESS = 'EDIT_ROOM_CATEGORIES_SUCCESS';
export const EDIT_ROOM_CATEGORIES_FAIL = 'EDIT_ROOM_CATEGORIES_FAIL';

export const GET_ROOM_CATEGORIES_INFO = 'GET_ROOM_CATEGORIES_INFO';
export const GET_ROOM_CATEGORIES_INFO_SUCCESS = 'GET_ROOM_CATEGORIES_INFO_SUCCESS';
export const GET_ROOM_CATEGORIES_INFO_FAIL = 'GET_ROOM_CATEGORIES_INFO_FAIL';

export const GET_ROOMS_CATEGORY_BY_ID = 'GET_ROOMS_CATEGORY_BY_ID';
export const GET_ROOMS_CATEGORY_BY_ID_SUCCESS = 'GET_ROOMS_CATEGORY_BY_ID_SUCCESS';
export const GET_ROOMS_CATEGORY_BY_ID_FAIL = 'GET_ROOMS_CATEGORY_BY_ID_FAIL';

export const GET_ROOMS = 'GET_ROOMS';
export const GET_ROOMS_SUCCESS = 'GET_ROOMS_SUCCESS';
export const GET_ROOMS_FAIL = 'GET_ROOMS_FAIL';

export const CREATE_ROOM = 'CREATE_ROOM';
export const CREATE_ROOM_SUCCESS = 'CREATE_ROOM_SUCCESS';
export const CREATE_ROOM_FAIL = 'CREATE_ROOM_FAIL';

export const EDIT_ROOM = 'EDIT_ROOM';
export const EDIT_ROOM_SUCCESS = 'EDIT_ROOM_SUCCESS';
export const EDIT_ROOM_FAIL = 'EDIT_ROOM_FAIL';

// add hotel rooms
export const ADD_ROOM = 'ADD_ROOM';
export const ADD_ROOM_SUCCESS = 'ADD_ROOM_SUCCESS';
export const ADD_ROOM_FAIL = 'ADD_ROOM_FAIL';

export const REMOVE_ROOM = 'REMOVE_ROOM';

export const CLEAR_SELECTED_ROOMS = 'CLEAR_SELECTED_ROOMS';

export const BOOK = 'BOOK';
export const BOOK_SUCCESS = 'BOOK_SUCCESS';
export const BOOK_FAIL = 'BOOK_FAIL';