export const SET_CURRENT_ROOM_CATEGORY = 'SET_CURRENT_ROOM_CATEGORY';

export const ADD_ROOM = 'ADD_ROOM';

export const REMOVE_ROOM = 'REMOVE_ROOM';

export const GET_ROOM_CATEGORIES = 'GET_ROOM_CATEGORIES';
export const GET_ROOM_CATEGORIES_SUCCESS = 'GET_ROOM_CATEGORIES_SUCCESS';
export const GET_ROOM_CATEGORIES_FAIL = 'GET_ROOM_CATEGORIES_FAIL';

export const GET_ROOMS = 'GET_ROOMS';
export const GET_ROOMS_SUCCESS = 'GET_ROOMS_SUCCESS';
export const GET_ROOMS_FAIL = 'GET_ROOMS_FAIL';

export const GET_ROOMS_CATEGORY_BY_ID = 'GET_ROOMS_CATEGORY_BY_ID';
export const GET_ROOMS_CATEGORY_BY_ID_SUCCESS = 'GET_ROOMS_CATEGORY_BY_ID_SUCCESS';
export const GET_ROOMS_CATEGORY_BY_ID_FAIL = 'GET_ROOMS_CATEGORY_BY_ID_FAIL';
