// profile management
export const UPDATE_PROFILE = 'UPDATE_PROFILE';
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS';
export const UPDATE_PROFILE_FAIL = 'UPDATE_PROFILE_FAIL';

// get profile info
export const GET_PROFILE_SUBSCRIPTIONS = 'GET_PROFILE_SUBSCRIPTIONS';
export const GET_PROFILE_SUBSCRIPTIONS_SUCCESS = 'GET_PROFILE_SUBSCRIPTIONS_SUCCESS';
export const GET_PROFILE_SUBSCRIPTIONS_FAIL = 'GET_PROFILE_SUBSCRIPTIONS_FAIL';
