// profile management
export const UPDATE_PROFILE = 'UPDATE_PROFILE';
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS';
export const UPDATE_PROFILE_FAIL = 'UPDATE_PROFILE_FAIL';

// get profile info
export const GET_PROFILE_SUBSTITUTIONS = 'GET_PROFILE_SUBSTITUTIONS';
export const GET_PROFILE_SUBSTITUTIONS_SUCCESS = 'GET_PROFILE_SUBSTITUTIONS_SUCCESS';
export const GET_PROFILE_SUBSTITUTIONS_FAIL = 'GET_PROFILE_SUBSTITUTIONS_FAIL';
