// get bookings from all users
export const SORT_BOOKINGS = 'SORT_BOOKINGS';
export const SORT_BOOKINGS_SUCCESS = 'SORT_BOOKINGS_SUCCESS';
export const SORT_BOOKINGS_FAIL = 'SORT_BOOKINGS_FAIL';

// change rooms status
export const CHANGE_BOOKING_STATUS = 'CHANGE_BOOKING_STATUS';
export const CHANGE_BOOKING_STATUS_SUCCESS = 'CHANGE_BOOKING_STATUS_SUCCESS';
export const CHANGE_BOOKING_STATUS_FAIL = 'CHANGE_BOOKING_STATUS_FAIL';

// get orders from all users
export const SORT_ORDERS = 'SORT_ORDERS';
export const SORT_ORDERS_SUCCESS = 'SORT_ORDERS_SUCCESS';
export const SORT_ORDERS_FAIL = 'SORT_ORDERS_FAIL';

// change order status
export const CHANGE_ORDER_STATUS = 'CHANGE_ORDER_STATUS';
export const CHANGE_ORDER_STATUS_SUCCESS = 'CHANGE_ORDER_STATUS_SUCCESS';
export const CHANGE_ORDER_STATUS_FAIL = 'CHANGE_ORDER_STATUS_FAIL';